### ISSUE TITLE
Does not link under OSX 

### ISSUE THREAD

**Issue by spachner** [pasccom/QTestLibPlugin#2]
Many thanks for doing the port work to QTC 4. I gave them a try at OSX:
`
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -weak_framework XCTest -Wl,-rpath,/Users/spachner/Qt-5.6/5.6/clang_64/lib -o release/plaintextqtestlibparsertest .obj_unix/plaintextqtestlibparsertest.o .obj_unix/plaintextqtestlibparserfactoryfake.o .obj_unix/moc_plaintextqtestlibparserfactoryfake.o   -F/Users/spachner/Qt-5.6/5.6/clang_64/lib ../common/release/libtestcommon.a /Users/spachner/localPrograms/QTCreatorPlugins/QTestLibPlugin-0.0.5/plugin/QTestLibPlugin/release/libqtestlibplugin.a -L/Users/spachner/localPrograms/qt-creator-opensource-src-4.0.0/bin/Qt\ Creator.app/Contents/Frameworks -L/Users/spachner/localPrograms/qt-creator-opensource-src-4.0.0/bin/Qt\ Creator.app/Contents/PlugIns -lCore -lProjectExplorer -lQmakeProjectManager -lTextEditor -lQtSupport -lCppTools -lResourceEditor -lQtcSsh -lQmlJS -lCPlusPlus -lAggregation -lExtensionSystem -lUtils -lLanguageUtils -Wl,-rpath=/Users/spachner/localPrograms/qt-creator-opensource-src-4.0.0/bin/Qt\ Creator.app/Contents/PlugIns -Wl,-rpath=/Users/spachner/localPrograms/qt-creator-opensource-src-4.0.0/bin/Qt\ Creator.app/Contents/Frameworks -framework QtWidgets -framework QtGui -framework QtTest -framework QtXml -framework QtNetwork -framework QtConcurrent -framework QtCore -framework OpenGL -framework AGL 
ld: unknown option: -rpath=/Users/spachner/localPrograms/qt-creator-opensource-src-4.0.0/bin/Qt Creator.app/Contents/PlugIns
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [release/plaintextqtestlibparsertest] Error 1
make[1]: *** [sub-PlainTextQTestLibParserTest-make_first-ordered] Error 2
make: *** [sub--Users-spachner-localPrograms-QTCreatorPlugins-QTestLibPlugin-0-0-5-tests-make_first-ordered] Error 2`

spachner

**Comment by pasccom** [comment]
Hello,
    Thanks for testing!
    That is due to using rpath for the parsers tests (done outside Qt Creator for simplicity). A priori, the flags are not the same for clang and gcc.
    I will try to find a more general solution this evening. The plugin should still compile, but you have to disable out of tree tests:
    -Either by disabling BUILD_TESTS in QTestLibPlugin.pri (which disables all tests)
    -Or by commenting the line SUBDIRS += tests in QTestLibPlugin.pro (disables only out of tree tests)
    Best regards,
Pasccom

**Comment by spachner** [comment]
ok, now it works.

o I commented the BUILD_TESTS in QTestLibPlugin.pri and linking was successfull.
o Still little glitches which I could solve by myself.

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -stdlib=libc++ -Wl,-rpath,@loader_path/../,-rpath,@executable_path/../ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/spachner/Qt-5.6/5.6/clang_64/lib -single_module -dynamiclib -Wl,-install_name,@rpath/PlugIns/libQTestLibPlugin.dylib -o libQTestLibPlugin.dylib .obj/release-shared/qtestlibplugin.o .obj/release-shared/qrc_qtestlibplugin.o .obj/release-shared/moc_qtestlibplugin.o  -F/Users/spachner/Qt-5.6/5.6/clang_64/lib release/libqtestlibplugin.a -L/Users/spachner/localPrograms/qt-creator-opensource-src-4.0.0/bin/Qt\ Creator.app/Contents/Frameworks -L/Users/spachner/localPrograms/qt-creator-opensource-src-4.0.0/bin/Qt\ Creator.app/Contents/PlugIns -lCore -lProjectExplorer -lQmakeProjectManager -lTextEditor -lQtSupport -lCppTools -lResourceEditor -lQtcSsh -lQmlJS -lCPlusPlus -lAggregation -lExtensionSystem -lUtils -lLanguageUtils -L/Users/spachner/Library/Application\ Support/QtProject/Qt\ Creator/plugins/4.0.0 -framework QtWidgets -framework QtGui -framework QtXml -framework QtConcurrent -framework QtNetwork -framework QtCore -framework OpenGL -framework AGL  
ld: warning: directory not found for option '-L/Users/spachner/Library/Application Support/QtProject/Qt Creator/plugins/4.0.0'
mv -f libQTestLibPlugin.dylib ../../bin/ 
cd translations/ && ( test -e Makefile || /Users/spachner/Qt-5.6/5.6/clang_64/bin/qmake /Users/spachner/localPrograms/QTCreatorPlugins/QTestLibPlugin-0.0.5/translations/translations.pro -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
/Users/spachner/Qt-5.6/5.6/clang_64/bin/lrelease qtestlibplugin_en.ts -qm /Users/spachner/localPrograms/QTCreatorPlugins/QTestLibPlugin-0.0.5/bin/qtestlibplugin_en.qm
Updating '/Users/spachner/localPrograms/QTCreatorPlugins/QTestLibPlugin-0.0.5/bin/qtestlibplugin_en.qm'...
    99 Übersetzungen wurden erzeugt (99 abgeschlossen und 0 nicht abgeschlossen)
/Users/spachner/Qt-5.6/5.6/clang_64/bin/lrelease qtestlibplugin_fr.ts -qm /Users/spachner/localPrograms/QTCreatorPlugins/QTestLibPlugin-0.0.5/bin/qtestlibplugin_fr.qm
Updating '/Users/spachner/localPrograms/QTCreatorPlugins/QTestLibPlugin-0.0.5/bin/qtestlibplugin_fr.qm'...
    99 Übersetzungen wurden erzeugt (99 abgeschlossen und 0 nicht abgeschlossen)`

o I created the missing directory: 
`mkdir -p "/Users/spachner/Library/Application Support/QtProject/Qt Creator/plugins/4.0.0"`

o And copied the lib: 
`cp ./QTestLibPlugin-0.0.5/QTestLibPlugin-0.0.5/bin/libQTestLibPlugin.dylib "/Users/spachner/Library/Application Support/QtProject/Qt Creator/plugins/4.0.0`

Now the plugin showed up in QTCreator and works.

Again, thanks for your effort.

spachner
