### ISSUE TITLE
Detect test executables that run multiple tests

### ISSUE THREAD

**Issue by martonb** [pasccom/QTestLibPlugin#3]
We have a large(ish) project and lots of tests. We noticed that creating a separate executable for each test class increases linking time quite a lot, so we created multiple (but less than previously) test executables that each run multiple (related) tests calling QTest::qExec multiple times from the same main() function.
BUT... We noticed, that running all tests from Qt Creator doesn't run these tests, but only the single tests declared with QTEST_APPLESS_MAIN / QTEST_GUILESS_MAIN / QTEST_MAIN.

See a detailed description here: https://gist.github.com/oranja/c032d7f77becca18137d49251e791593

So, it would be nice, if:
1. additional texts that this plugin looks for to detect test classes, could be configured in the plugin's options
OR
2. instead of looking for test classes, look for test projects (search keywords "testcase" / "testlib" in the .pro file and include .pri files?). Then run the detected executables' main() function and parse the output.
3. any other solution that would allow us running multiple tests from a single executable and still be compatible with this plugin.

**Comment by pasccom** [comment]
Hello,
    I guess you are not using my plugin to run your tests in QtCreator. It is a plugin I developed to run tests automatically under QtCreator 3.6.0, I maintain it beacause it has some interesting features (to my mind) not included in the official plugin. The official test runner plugin included in QtCreator (from 4.0.0) is called **AutoTest**. You should use the usual request system for Qt Creator <https://bugreports.qt.io> to submit your request.
    Actually, if you were using my plugin, you should be able to run tests as you request, since I followed your second idea: The plugin uses qMake parser to detect tests projects (with testlib in QT variable). Currently this is the only supported parser (no CMake, but this can easily be extended).
    Best regards,
Pasccom

**Comment by martonb** [comment]
(facepalm) I was redirected here from an article, sorry :D
I'll log my improvement task there too...

Done: https://bugreports.qt.io/browse/QTCREATORBUG-18347
Thanks!
